services:
  ak2_postgres:
    build:
      context: ./ak2_postgre
      dockerfile: DockerFile
    volumes:
      - ../ak2_db/ak2AllTables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "13306:5432"
    privileged: true
  ak2_front_apache:
    build: 
      context: ./ak2_front_apache
      dockerfile: DockerFile
    ports:
      - 40081:80
      - 40444:443
    volumes:
      - ./ak2_front_apache/keys:/etc/ssl-key:ro
      - ./ak2_front_apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./ak2_front_apache/conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
      - ./ak2_front_apache/logs:/usr/local/apache2/logs
      - ../ak2-server-conf/ak2-front/front.ak2_proxy.conf:/etc/custom/conf/proxypass.conf
    environment:
      - TZ=Asia/Tokyo
    privileged: true
  ak2_front:
    build: 
      context: ./ak2_front
      dockerfile: DockerFile
    ports:
      - 40080:80
      - 40443:443
    volumes:
      - ./ak2_front/keys/server.pem:/etc/nginx/ssl/server.pem:ro
      - ./ak2_front/keys/server.key:/etc/nginx/ssl/server.key:ro
      - ./ak2_front/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
    privileged: true
  ak2_static:
    build:
      context: ./ak2_static
      dockerfile: DockerFile
    ports:
      - 11080:80
      - 11443:443
    volumes:
      - ./ak2_static/keys/server.pem:/etc/nginx/ssl/server.pem:ro
      - ./ak2_static/keys/server.key:/etc/nginx/ssl/server.key:ro
      - ./ak2_static/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
    privileged: true
  squid:
    build:
      context: ./squid
      dockerfile: DockerFile
      args:
        BASE_IMAGE: "ubuntu/squid:latest"
    platform: linux/amd64
    ports:
      - "13128:3128"
    volumes:
      - ./squid/conf:/etc/squid:ro
    privileged: true
    links:
      - ak2_front:ak2.prod.jp.local
      - ak2_static:ak2.styles.jp.local
  redis:
    build: 
      context: ./redis
      dockerfile: DockerFile
    command: /bin/bash /conf/cluster-builder.sh
    ports:
      - 7001-7006:7001-7006
    volumes:
      - ./redis/conf:/conf